// <auto-generated />
using System;
using EFCore_DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore_DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529055518_Identity_MOD")]
    partial class Identity_MOD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCore_Model.Models.Book", b =>
                {
                    b.Property<int>("IDBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 5)
                        .HasColumnType("decimal(10,5)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("IDBook");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            IDBook = 1,
                            ISBN = "12345",
                            Price = 100m,
                            Title = "Advtures od Tintin"
                        },
                        new
                        {
                            IDBook = 2,
                            ISBN = "12345",
                            Price = 100m,
                            Title = "Advtures od Tintin"
                        },
                        new
                        {
                            IDBook = 3,
                            ISBN = "12345",
                            Price = 100m,
                            Title = "Advtures od Tintin"
                        },
                        new
                        {
                            IDBook = 4,
                            ISBN = "12345",
                            Price = 100m,
                            Title = "Advtures od Tintin"
                        },
                        new
                        {
                            IDBook = 5,
                            ISBN = "12345",
                            Price = 100m,
                            Title = "Advtures od Tintin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
